language: ruby

install:
  - bundle install

before_script:
  - travis_retry gem install htmlproof
  
script: jekyll build && htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
